### ISSUE TITLE
Possible to make this on click instead of on hover? 

### ISSUE THREAD

**Issue by jonasflint** [Skullsneeze/SidebarHoverToggle#2]
Man, the hover function can get somewhat annoying. I realize we can toggle via a hotkey, but this would be pretty convenient if we can just use a mouse click on the gutter or a button to toggle the sidebar.

**Comment by Skullsneeze** [comment]
Hi, Sorry for the delayed response. Work has been a bit crazy lately.

As for the feature, I was thinking of adding a setting that would let the user choose between hover or click functionality.

I'll try to work on this asap. Thanks for the feedback!

**Comment by Skullsneeze** [comment]
I've just updated the master branch to make this option available. Please check out the updated readme, since this new addition does require another package to work.

If you run into any issues, please let me know!
