### ISSUE TITLE
How can i change the speed to open the sidebar when hover?

### ISSUE THREAD

**Issue by luis-patvillaruz** [Skullsneeze/SidebarHoverToggle#3]
As title says.. Thanks!

**Comment by Skullsneeze** [comment]
Hi luiz, unfortunately there is no way to change the speed, since I'm using sublime's built-in hover function (used for tooltips I believe). You could request an option for this with the sublime dev team.

**Comment by Skullsneeze** [comment]
I'll close this issue for now, since unfortunately there isn't much I can change on my end in this case. I will however keep an eye on this so that when this becomes possible it can be implemented.

**Comment by Skullsneeze** [comment]
@luis-patvillaruz As a little follow up, for issue #2 I added the possibility to toggle the sidebar on click, which takes out the hover delay. This might work as a solution for now!
