### ISSUE TITLE
Click to toggle not working. 

### ISSUE THREAD

**Issue by jonasflint** [Skullsneeze/SidebarHoverToggle#4]
I put the following in my sublime settings:

`"sidebar_toggle_on_click": true,`

And it's just not working....

screenshot: 
http://d.pr/i/ZY4RFd

I'd rather just toggle she sidebar on click...

**Comment by Skullsneeze** [comment]
Hi Jonas,

Thanks for reporting the issue. I will look into it asap. Just to be sure, did you install the latest dev version? The package that is currently available through package control does not have this feature yet.

**Comment by Skullsneeze** [comment]
I've tried reproducing this issue, and was unable to do so.

I've installed the plugin using the instructions provided in the readme.

Also, please note that you will need the MouseEventListner plugin (available through package control) for the on click functionality to work.

Another note: The event is triggered by clicking on the gutter (bar with line numbers).

Please let me know if you are able to get everything to work.

**Comment by jonasflint** [comment]
Hey, Yeah, I downloaded the one through package control. I just used the updated one and can confirm that it works as specified!. Great plugin! keep it up!
