### ISSUE TITLE
Do not auto hide side bar

### ISSUE THREAD

**Issue by natanfelles** [Skullsneeze/SidebarHoverToggle#5]
Hi, thanks for this awesome package.

What do you think about do not auto hide the side bar?

Then just hide/show just if the mouse hover the left side. Enabling a possible persistent state.

**Comment by Skullsneeze** [comment]
Hi @natanfelles. Thanks for the request, and sorry for the delayed reply. I'll look into the possibilty of adding this feature, perhaps through a user preference setting. I'll let you know once things get updated!

**Comment by Skullsneeze** [comment]
@natanfelles I'm glad to say I added the option, and have created a new release which contains this feature (amongst some other small updates). You can upgrade the package through Sublime text, and use the following setting to turn auto hiding on or off.

`"sidebar_toggle_auto_hide": false`

Please close this issue if this new feature works for you. If there are any issues, please let me know!

**Comment by natanfelles** [comment]
Hello, @Skullsneeze ! 

I just updated the package and it works fine.

His project inspired me to do an update on [an interface](https://github.com/natanfelles/adminer-bootstrap-like), which had a button to open and close the sidebar. Then I implemented something more practical, alternating with the mouse hover.

I recorded [a video](https://www.youtube.com/watch?v=fMFCuaJphVk). I think it would be nice to have this kind of alternation on the sidebar of the sublime. But I do not know if it's possible to implement this.

Closing here. Thank you very much. 😃 

If you have time to consider the proposal, I think it's good. Thank you.

**Comment by Skullsneeze** [comment]
@natanfelles, Glad to hear the issue got resolved!

Also, that looks pretty neat! Unfortunately the plugins in sublime are quite limited because they have to make use of the sublime API.

I guess there is probably some way of doing this, but unfortunately my knowledge of python wouldn't be up for the challenge at the moment 😜
