### ISSUE TITLE
User preferences don't seem to work

### ISSUE THREAD

**Issue by simonewebdesign** [Skullsneeze/SidebarHoverToggle#6]
Hi, I just added this to my user preferences:

```
"sidebar_toggle_on_hover": false,
"sidebar_toggle_on_click": false,
```

Then I restarted Sublime, but the sidebar is still toggling. Am I missing something?

Great package by the way :)

**Comment by Skullsneeze** [comment]
Hi @simonewebdesign That's strange. I'll have a look to see what might be going wrong, and will let you know what a possible solution might be!

**Comment by Skullsneeze** [comment]
@simonewebdesign I've just tested this issue locally, and the settings seem to be working for me.

What I did notice was that you set both settings to "false". This would mean that the sidebar can't be toggled by hovering, and clicking.

Please try setting one of the settings to true to see if that solves the issue.

**Comment by simonewebdesign** [comment]
I tried:

```
"sidebar_toggle_on_click": true,
"sidebar_toggle_on_hover": false,
"sidebar_toggle_auto_hide": false,
```

But still the sidebar won't stop toggling on hover (and it automatically hides when I move the cursor away). Looks like it's ignoring the settings altogether?

I also tried to see if there are any errors in the console, but I don't see any.

I'm using ST 3.0, build 3143 by the way.

**Comment by Skullsneeze** [comment]
@simonewebdesign Please make sure that you have the latest updates. I've just released a new version which solves some other issues, and might also solve your issue. You can upgrade the package through the sublime package control, using the "Upgrade package" command.

Please let me know if this solves your issue.

**Comment by simonewebdesign** [comment]
Seems to be working fine now - thank you! :)
